apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:9CH1tGLoVstxryGqFF+Fukr5dCeoijP0WyWHbtCwaOI=,iv:2O3AIdL2gVwB+5inNjFUBF8oAfoxqQ42q9SKZ+aUKr8=,tag:PtPcAaEK7Bi2dFVE4lu2Yg==,type:str]
sops:
  age:
    - recipient: age1vtv0q662xperfvqhnxxymu5upj4gypxmhr4u9l2p5k6ac4us4v9sccnznv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TXp3MWt2SklYbkNyTWR4
        NWRFc2pTVzdhSmIxckNKclVJRGNjS253d1VvCll4c1JUL21FZmNBcEpjRVc5SEc0
        eGs5c281NElTdEw5cXVBTzN3ZCt6MFEKLS0tIHBxc25QWEV3alZ3QXltVnZyN0hC
        NlNXYVdCT2dTYXFlTFdSdDVOOUhiVG8KvwdLS46luJ407gYWOGxBSGxM0AKfYMTK
        7g+qP6QpfETLb4jJTaWLT26qcbGw8lDXLeJ+hVPGGT8PVi4DCbHYvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T12:40:20Z"
  mac: ENC[AES256_GCM,data:XdeYGM61nK5Em8aKy5iau7+oiUjGC+THUiwTmvms2Dz0WDSu27zyKFf7iLFziDNg7SWtLNtZYcQc33GunrjRD6SY/q1TgXgCr2TAc5JgRmLRqlVXx/YB+VYQghPhHx+81l8AgrVl/fKS71JR3rZtQTdNMGX08jqUewiYxkTcd1A=,iv:Nj0UVOPjY4BQQAy4URrz+z5oBbmAhr2836mP2kXLS2s=,tag:03lcKJ/OvxNhosAIeCyKZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
