apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:GNe2C9yCXe8n2mIRbkOSlu4dZr9x+yMdvGavxvXp9jaP3vLlynpdgR9bZ/OGG+xgKv8ed/yuywwRPKm8Zi9gYl7WJ6rp5j0ooUuTSWedq89pJwRdw0CFJTEsFUqHeYAiZM2za3iiFKSeuw9fDs7C6gdktpMWMb3ZhcRa8I6JpmEvrgBiUAVYzD1Z0VzFGyU0JLmn70uqgo/Yx+heYhKImr5JAHiVFbp3yY6Y8sT8qNzDYnbQ,iv:Bo+z583PNU1OB75V5s3KnaFTsHnOUGPVNFTkgYIp3KU=,tag:picMqJrokEuji20nhvPyTA==,type:str]
sops:
  age:
    - recipient: age1vtv0q662xperfvqhnxxymu5upj4gypxmhr4u9l2p5k6ac4us4v9sccnznv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM0NrNldIRCtnamNZSUtG
        ZjJDVkdnM0FJaUVsMmtiL2NGblA4cmkvTWdBCkhTTUhmc0JhSmJUV2ZBWWhaLzg2
        bTZneEJ6Y211WVBjZ1BsOE5GVjJmUGsKLS0tIFdMTDltUC9pdWRoVFJ6ZkhVekNn
        ZnpqUnUyK0xyRGtlRXZqcDk2bHFKRDAK/Ddb8shTM5OgDvW9KEDPGrn0dI6FHzcr
        m9YxmngD0NwQyudj+UqE501JGajbBZFN7Xq7TiWg+W0AFhRPu7jhcw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T12:40:20Z"
  mac: ENC[AES256_GCM,data:WEWPw91PuvFM67EPnxQ630Py4a4B3BZVqwYegQmBu+md8FruvH6cgsvJOGnj2mPSlsS55dof65YGAaDLrc4pm4IZPfSR2+sTbNo5B83aTw/oWVQtXP9rhzjgQrRSMlhg/7wxZu6iok8xxv6zFJqjwuw2t58d3pJPejppwQR8wl0=,iv:v5HI44PQ7KYJ+bP8Uu6VjN3YfTLp3Fz9/NCMm3g3gQ0=,tag:CXxcGpF4ItDuYFN6reeaWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
