apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:yiE1a6OmSeAQ4Z8lfmEK5bAa3zEGZguz8YoYXWeCcQj/YUpBpcnyIQ==,iv:DEEBMba+6CfeYRtETVF5EY7FZyhn7FiAgqJBzLcO8LA=,tag:13Gk+nC0NYa0OBA/PEdzZA==,type:str]
sops:
  age:
    - recipient: age1vtv0q662xperfvqhnxxymu5upj4gypxmhr4u9l2p5k6ac4us4v9sccnznv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM2doWFlXbzE4dUJKbmww
        d1UvaUJqUEpJRjhGeGVmRWplY0RkTUg2NVM4Cm5oaXp6SDZRV3pHUFdTWlJBbEpV
        TzA5UDdJYllOVnVxRUtoVUFMVWlDRzQKLS0tIHJ5UHN4eXc0VUdkZ3VpaU93c2FP
        am9FNUtvUHlWVDNLWGJLeTFyTWhrbFEKIcrrzSj9uq0EfVNZvVnn4d/O5eOQ/eAv
        oyrbJxTdcMDMET/W39m5J5h+sCLNSFvjpbj1qL8zGYY/O24iM3IFuw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T12:40:20Z"
  mac: ENC[AES256_GCM,data:mQO2Ed3r2dIB/1N5ZGSWqFryxcBQCYAKGQVkIOXIM4I6s05PyWzfkttAEntja/RKCV1NqaypROwACmTNnpoNJnoWU8FpB99gOjgNNH8ohA1ujNtXM6n9tvR2qVCGHd3+aunIqr/pKylzxsVOnCQ+Tab/ZrgQM0fi9IMYp5bKcBI=,iv:NQ8nODzhrsuvZsSTtzHpO4qSVQ4qdg7e+ZUbS0A3Nck=,tag:hqj1/FwUVBnJFGQru/i9mQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
