machine:
  kubelet:
    extraConfig:
      serializeImagePulls: false
    nodeIP:
      validSubnets:
        - 172.16.0.0/24
    extraMounts:
      - destination: /var/mnt/longhorn
        type: bind
        source: /var/mnt/longhorn
        options:
          - bind
          - rshared
          - rw

---
apiVersion: v1alpha1
kind: UserVolumeConfig
metadata:
  name: longhorn
provisioning:
  diskSelector:
    match: disk.dev_path == '/dev/sdb'
  minSize: 50GB